#pragma once
#include "Shader3D_Component.h"
#include "Shader3D_Light.h"
#include "Shader3D_normal.h"
#include "Shader3D_Tex.h"
#include "Shader3D_TexLight.h"
#include "Shader3D_SkyBox.h"
#include "Shader2D_Component.h"
#include "Shader2D_Line.h"